groups:
  - name: nodeExporter
    rules:
      - alert: nodeDown
        expr: up == 0
        for: 5s
        labels:
          status: High
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 30s."
