version: '3.1'

services:
  golang_1.19:
    build: ./go1.19
    container_name: golang_119
    volumes:
      - ~/workspace/:/root/workspace
    tty: true
    ports:
      - 5060:5060/udp
      - 8090:8090
