version: '3.1'

services:
  mozi_dev:
    build: mozi_dev
    container_name: mozi_dev
    volumes:
#      - /etc/localtime:/etc/localtime:ro
      - ~/workspace:/root/workspace
      - ~/workspace/code/hiar_mozi/mozi-ar-render-service/internal/module/ar_render/service/mozi_render/libs:/app/mozi_render/libs #ptz ocr
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
      - ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
    tty: true
#    network_mode: host
    ports:
      - 8109:8109
      - 16060:6060
      - 9113:9113
      - 9112:9112
      - 8112:8112
      - 8113:8113

  mozi_dev_1804:
    build: mozi_dev_1804
    container_name: mozi_dev_1804
    volumes:
      - ~/workspace:/root/workspace
      - ~/workspace/code/hiar_mozi/mozi-ar-render-service/internal/module/ar_render/service/mozi_render/libs:/app/mozi_render/libs #ptz ocr
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
      - ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
#    network_mode: host
    tty: true
    ports:
      - 8109:8109

  golang_1.19:
    build: golang_env/go1.19
    container_name: golang_119
    volumes:
      - ~/workspace/:/root/workspace
    tty: true
    ports:
      - 5060:5060/udp
      - 8090:8090

  centos7.6:
    build: centos7.6
    container_name: centos7.6
    volumes:
      - ~/:/root/
      - /dev:/dev
      - /run/dbus:/run/dbus
      - /var/run/dbus:/var/run/dbus
    tty: true
    network_mode: host
