version: '3.7'
services:
  master:
    image: redis:6.0
    container_name: redis_master
    restart: always
    volumes:
      - ./redis_master.conf:/usr/local/etc/redis/redis.conf
      - ${STORAGE_PATH}/redis_master:/data
    command:
      redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_AUTH}
    ports:
      - ${REDIS_MASTER_PORT}:6379

  redis_slave_1:
    image: redis:6.0
    container_name: redis_slave_1
    restart: always
    volumes:
      - ./redis_slave_1.conf:/usr/local/etc/redis/redis.conf
      - ${STORAGE_PATH}/redis_slave_1:/data
    command:
      redis-server /usr/local/etc/redis/redis.conf --slaveof ${HOST} ${REDIS_MASTER_PORT} --requirepass ${REDIS_AUTH} --masterauth ${REDIS_AUTH}
    ports:
      - ${REDIS_SLAVE_1_PORT}:6380

#  redis_slave_2:
#    image: redis:6.0
#    container_name: redis_slave_2
#    restart: always
#    volumes:
#      - ./redis_slave_2.conf:/usr/local/etc/redis/redis.conf
#      - ${STORAGE_PATH}/redis_slave_2:/data
#    command:
#      redis-server /usr/local/etc/redis/redis.conf --slaveof ${HOST} ${REDIS_MASTER_PORT} --requirepass ${REDIS_AUTH} --masterauth ${REDIS_AUTH}
#    ports:
#      - ${REDIS_SLAVE_2_PORT}:6381
