version: '3'

services:
  mysql:
    image: mysql:5.7.16
    container_name: common_mysql
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=Hiscene2022
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --sql-mode="STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    deploy:
      placement:
        constraints:
          - node.role==manager

  redis:
    image: redis:6.0.6
    container_name: common_redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
      - ./config/redis/redis.conf:/etc/redis/redis.conf
    environment:
      - TZ=Asia/Shanghai
    command:
      redis-server /etc/redis/redis.conf --requirepass Hiscene2022

  emqx:
    image: emqx/emqx:4.3.2
    container_name: common_emqx
    restart: always
    ports:
      - "18083:18083" #后台访问端口 admin/public
      - "1883:1883" #MQTT 协议端口
      - "8084:8084"
      - "8883:8883" #MQTT/SSL 端口
      - "8083:8083" #MQTT/WebSocket 端口

  etcd:
    image: "quay.io/coreos/etcd:v3.4.10"
    container_name: common_etcd
    entrypoint: /usr/local/bin/etcd
    restart: always
    environment:
      - "ALLOW_NONE_AUTHENTICATION=yes"   #不用密码
    ports:
      - 2379:2379
    volumes:
      - ./data/etcd:/etcd_data

  mongodb:
    image: mongo:6.0.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/mongodb/configdb:/data/configdb
      - ./data/mongodb/db:/data/db
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 27017:27017
    deploy:
      placement:
        constraints:
          - node.role==manager

  nginx:
    restart: always
    container_name: nginx
    image: nginx
    ports:
      - 1001:80
      - 1443:443
    volumes:
      - /opt/logs/nginx:/var/log/nginx
      - ./nginx/www:/var/www
      - ./nginx/etc/cert:/etc/nginx/cert
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    environment:
      - NGINX_PORT=80
    privileged: true
