version: '3.1'

services:
  alert_hook:
    build: ./
    container_name: alert_hook
    image: alert_hook
    ports:
      - 9092:9092
    volumes:
      - /opt/logs/alert_hook/:/opt/logs/alert_hook/
    environment:
      alertType: dindin #dindin、wechat
      alertToken: 7e5bf3d1d1e82f04462ed2c47a1b27d3c5ce609e0d91ccbd3ad6044dbf33cf9c

