version: '3'

services:
  minio:
    image: minio/minio:RELEASE.2020-01-16T03-05-44Z
    container_name: minio
    restart: always
    ports:
      - 8802:9000
    volumes:
      - ${MINIO_EXTERN_PATH}:/data
      - ${MINIO_EXTERN_CONFIG}:/root/.minio
    logging:
      driver: json-file
      options:
        max-size: "2000M"
        max-file: "10"
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: hiDroneoss2020.
    command: server /data

  minio_resizer:
    build: ./
    image: minio_resizer
    container_name: minio_resizer
    restart: always
    ports:
      - 8803:80
    volumes:
      - ${MINIO_EXTERN_CACHE}:/data
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"
    environment:
      IMAGE_HOST: http://minio:9000 #minio的service_name
      NGINX_HOST: 127.0.0.1
